### ISSUE TITLE
getting Error on adding executable 

### ISSUE THREAD

**Issue by aadityaks** [corochann/SingleFileExecutionPlugin#3]
![screenshot from 2018-06-13 12-34-56](https://user-images.githubusercontent.com/32814053/41335408-53d984b2-6f06-11e8-93b3-ec2fb9ebd960.png)
getting error as shown in right hand bottom corner of image

**Comment by corochann** [comment]
Can you try creating `CMakeLists.txt` file?

**Comment by aadityaks** [comment]
For a project, it's automatically created but for a single file, I don't know how to link that to an executable that's still I am figuring out so if possible could you just throw some light upon this 
Thanks

**Comment by corochann** [comment]
Actually, even for single file execution, I would like you to create/start as a project. Then `CMakeLists.txt` is automatically created and you can use this `CMakeList.txt` file for building several `cpp` file with several executables.

Your project directory structure should be...

project-dir (your directory name is a.cpp in above picture)
 |- a.cpp (source file)
 |- CMakeLists.txt


Then, inside of the CMakeLists.txt should be,

```
cmake_minimum_required(VERSION 3.10)
project(a.cpp)

set(CMAKE_CXX_STANDARD 14)

add_executable(main a.cpp)
```

**Comment by aadityaks** [comment]
thanks @corochann  for your valuable inputs
